" Install packages and configuration
call plug#begin()
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive', { 'on': 'Gstatus' }
Plug 'junegunn/fzf'
call plug#end()

" Settings
let mapleader = " "

" Keybindings

" Project management
map \ :NERDTreeToggle<CR>

" General
map <leader><leader> :
imap jk <ESC>
