" Install packages and configuration
call plug#begin()
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive', { 'on': 'Gstatus' }
call plug#end()

" Project management
map \ :NERDTreeToggle<CR>
